export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/font/index',
    'pages/size/index',
    'pages/shadow/index',
    'pages/border/index',
    'pages/spacing/index',
    'pages/shortcuts/index',
    'pages/class/index',
    'pages/color/index',
    'pages/attributify-mode/index',
    'pages/animation/index',
    'pages/rpxTranform/index',
    'pages/bg/index',
    'pages/odd-even/index',
    'pages/first-last/index',
    'pages/divide/index',
    'pages/space/index',
    // 'pages/icon/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
})
